### ISSUE TITLE
s3_enable_access_logging job is missing minimal permissions and needs more meaningful logs

### ISSUE THREAD

**Issue by martinianodl** [vmware-samples/secure-state-remediation-jobs#5]
When running the s3_enable_access_logging job without the `s3:ListBucket` permissions I'm getting this error: `botocore.exceptions.ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden`.

The job has two issues that needs to be addressed:

1. The list of minimal permissions needs to be updated with `s3:ListBucket`
2. The job should have a more meaningful error when the user doesn't have the correct permissions.

Thanks

**Comment by vikramsinghvirdi** [comment]
Resolved in release V1.0.0
https://github.com/vmware-samples/secure-state-remediation-jobs/pull/7
